Doc(core): Input component
moaijs/moai pull request #180
Opened 2021-05-13 14:20 UTC by monodyle

2021-05-13 14:24 UTC, ng-hai commented on core/src/input/input.stories.tsx
> +Simply example when using Input with form. For advenced, see [Form][form] section.
Grammar "advenced"

2021-05-13 21:48 UTC, thien-do requested changes
This is actually pretty good, @monodyle . Only requesting change for:
- Minor issues that I commented
- Also please register a free account at Grammarly and let it checks the text you used here. It's pretty simple, actually, just select all and paste them to their app

2021-05-13 21:48 UTC, thien-do commented on core/src/input/input.tsx
> +	 * [3]: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist
This is weird.. the change from "1" to "3". I think you would not need this since the numbering reset on every comment block

2021-05-13 21:48 UTC, thien-do commented on core/src/input/input.tsx
> +	 * [4]: /docs/guides-icons--primary
Good.. you know to link to my not-written yet page :))

2021-05-13 21:48 UTC, thien-do commented on core/src/input/input.tsx
>  	autoSelect?: boolean;
Please help me remove this

2021-05-13 21:48 UTC, thien-do commented on core/src/input/input.tsx
>  	"aria-labelledby"?: string;
Good

2021-05-13 21:48 UTC, thien-do commented on core/src/input/input.tsx
> +	 * A value is required or must be check before form submission
"must be check".. you copy, right :))

2021-05-13 21:48 UTC, thien-do commented on core/src/input/input.stories.tsx
> +		list: _Story.arg(null, "Controlled"),
I don't think "list" should be a part of the "Controlled" group. It also works in uncontrolled input. Should move it to the "Attributes" group.

2021-05-13 21:48 UTC, thien-do commented on core/src/input/input.stories.tsx
> +		autoSelect: _Story.arg(null, "Attributes"),
Please help me remove this

2021-05-15 07:13 UTC, ng-hai approved these changes

2021-05-15 09:58 UTC, thien-do approved these changes
This is good. THank you. I'll approve this but if possible please don't merge it yet. I'm having a heavy refactor and when it's done, I'll update this PR for you

2021-05-15 11:29 UTC, merged